language: python
python:
    - "2.7"
virtualenv:
    system_site_packages: true
before_install:
    - sudo apt-get install python-numpy
    - pip install pytest pytest-cov
    - pip install coveralls

script:
    - python setup.py install
    - py.test

after_success:
    - coveralls
